site_name: "Random Generator Application"

theme:
  name: "readthedocs"

nav:
    - Project:
      - Home: index.md
      - Problem Statement: problem.md
      - Solution Journal : solution.md
      - REST API: rest_api.md
    - Reference Guide:
      - Core Module: ./reference/core.md
      - Hypothesis Module: ./reference/hypothesis.md
      - Histogram Module: ./reference/histogram.md
      - Endpoints Module: ./reference/endpoints.md
      - Routing Module: ./reference/routing.md
    - Tests Specification:
      - Core Tests: ./tests/test_core.md
      - Hypothesis Tests: ./tests/test_hypothesis.md
      - Histogram Tests: ./tests/test_histogram.md
      - Endpoints Tests: ./tests/test_endpoints.md
      - Routing Tests: ./tests/test_routing.md

plugins:
- search
- section-index